# Generated by Django 5.1.7 on 2025-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoundChat", "0008_remove_message_image_alter_message_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
