# Generated by Django 5.1.7 on 2025-03-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SoundChat", "0009_alter_message_options_alter_message_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp"]},
        ),
    ]
